export const APP_LOAD = "APP_LOADED";
export const HOME_PAGE_LOADED = "HOME_PAGE_LOADED";
export const HOME_PAGE_UNLOADED = "HOME_PAGE_UNLOADED";
export const ASYNC_START = "ASYNC_START";
export const ASYNC_END = "ASYNC_END";
export const MAP_PAGE_LOADED = "MAP_PAGE_LOADED";
export const SET_SELECTED_DESTINATION_FEATURES =
  "SET_SELECTED_DESTINATION_FEATURES";
export const LOAD_SEARCH_SUGGESTIONS = "LOAD_SEARCH_SUGGESTIONS";
export const SET_SUGGESTION_VALUE = "SET_SUGGESTION_VALUE";
export const SET_SELECTED_SUGGESTION = "SET_SELECTED_SUGGESTION";
export const UNSET_SELECTED_SUGGESTION = "UNSET_SELECTED_SUGGESTION";
